name: Deploy marketing site to Firebase Hosting on PR

on:
  workflow_dispatch:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: marketingSite
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHIELDBUG_MARKETING }}'
          projectId: shieldbug-marketing
          channelId: 'commit-${{ github.event.commits[0].id }}'